version: "3.3"

services:
  web:
    container_name: class-offer-service
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "9000:9000"

  db:
    image: 'mongo'
    restart: always
    container_name: 'db'
    ports:
      - "27017:27017"